<a href="https://colab.research.google.com/github/nanmaharaj/my-deeplearning-projects/blob/main/supervised_word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

In [34]:
reviews=['nice food',
         'amazing restaurant',
         'too good',
         'just loved it!',
         'will go again',
         'horrible food',
         'never go there',
         'poor service',
         'poor quality',
         'needs improvement']

sentiment=np.array([1,1,1,1,1,0,0,0,0,0])

In [36]:
one_hot("amazing restaurant",30)

[20, 10]

In [37]:
vocab_size=50
encoded_reviews=[one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[21, 48],
 [22, 42],
 [29, 9],
 [42, 22, 10],
 [44, 44, 31],
 [43, 48],
 [47, 44, 34],
 [36, 5],
 [36, 26],
 [43, 3]]

In [38]:
max_length=3
padded_reviews=pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[21, 48,  0],
       [22, 42,  0],
       [29,  9,  0],
       [42, 22, 10],
       [44, 44, 31],
       [43, 48,  0],
       [47, 44, 34],
       [36,  5,  0],
       [36, 26,  0],
       [43,  3,  0]], dtype=int32)

In [39]:
embedded_vector_size=4
model=Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length, name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [40]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy']
              )
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              200       
                                                                 
 flatten_3 (Flatten)         (None, 12)                0         
                                                                 
 dense_3 (Dense)             (None, 1)                 13        
                                                                 
Total params: 213 (852.00 Byte)
Trainable params: 213 (852.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [41]:
X=padded_reviews
y=sentiment

In [42]:
model.fit(X,y,epochs=50,verbose=0)

In [43]:
loss, accuracy=model.evaluate(X,y)
accuracy

1/1 [==============================] - 0s 87ms/step - loss: 0.6220 - accuracy: 1.0000


1.0

In [44]:
#we have solved food review problem to get word embeddings/ weights
weights=model.get_layer('embedding').get_weights()[0]
len(weights)

50

In [48]:
weights[21],weights[22]

(array([ 0.05450337, -0.05895551, -0.03285329, -0.05927309], dtype=float32),
 array([ 0.05910826, -0.01299043,  0.08330053, -0.00066076], dtype=float32))