<a href="https://colab.research.google.com/github/nanmaharaj/my-deeplearning-projects/blob/main/tensorflow_input_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import tensorflow as tf

In [36]:
daily_sales_numbers=[21,22,-108,31,-1,32,34,31]

In [37]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [38]:
for sales in tf_dataset:
  print(sales)
  print(sales.numpy())

for sales in tf_dataset.as_numpy_iterator():
  print(sales)

tf.Tensor(21, shape=(), dtype=int32)
21
tf.Tensor(22, shape=(), dtype=int32)
22
tf.Tensor(-108, shape=(), dtype=int32)
-108
tf.Tensor(31, shape=(), dtype=int32)
31
tf.Tensor(-1, shape=(), dtype=int32)
-1
tf.Tensor(32, shape=(), dtype=int32)
32
tf.Tensor(34, shape=(), dtype=int32)
34
tf.Tensor(31, shape=(), dtype=int32)
31
21
22
-108
31
-1
32
34
31


In [39]:
for sales in tf_dataset.take(3):
  print(sales.numpy())

21
22
-108


In [40]:
tf_dataset=tf_dataset.filter(lambda x: x>0)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

21
22
31
32
34
31


In [41]:
tf_dataset=tf_dataset.map(lambda x: x*72)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

1512
1584
2232
2304
2448
2232


In [42]:
tf_dataset=tf_dataset.shuffle(3)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

1584
1512
2448
2232
2304
2232


In [43]:
for sales_batch in tf_dataset.batch(3):
  print(sales_batch.numpy())

[2232 1584 2304]
[2232 1512 2448]


In [44]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset=tf_dataset.filter(lambda x: x>0).map(lambda y: y*72).shuffle(2).batch(2)
tf_dataset

<_BatchDataset element_spec=TensorSpec(shape=(None,), dtype=tf.int32, name=None)>

In [45]:
images_ds=tf.data.Dataset.list_files('/content/drive/MyDrive/images/*/*',shuffle=False)

In [46]:
for file in images_ds.take(3):
  print(file.numpy())

b'/content/drive/MyDrive/images/cat/00tb-cats1-mediumSquareAt3X.jpg'
b'/content/drive/MyDrive/images/cat/07CAT-STRIPES-mediumSquareAt3X-v2.jpg'
b'/content/drive/MyDrive/images/cat/1200px-Cat_August_2010-4.jpg'


In [47]:
class_names=["cat","dog"]

In [48]:
image_count=len(images_ds)
image_count

191

In [49]:
train_size=int(image_count*0.8)

train_ds=images_ds.take(train_size)
test_ds=images_ds.skip(train_size)

In [50]:
len(train_ds),len(test_ds)

(152, 39)

In [53]:
s='/content/drive/MyDrive/images/cat/00tb-cats1-mediumSquareAt3X.jpg'

s.split("/")[-2]

'cat'

In [55]:
import os
def get_label(file_path):
  return tf.strings.split(file_path, os.path.sep)[-2]

In [61]:
def process_image(file_path):
  label=get_label(file_path)

  img=tf.io.read_file(file_path)
  img=tf.image.decode_jpeg(img)
  img=tf.image.resize(img,(128,128))

  return img,label

In [63]:
train_ds=train_ds.map(process_image)
for img,label in train_ds.take(3):
  print("Image:", img)
  print("Label:",label)

Image: tf.Tensor(
[[[ 71.30945     34.30945     18.309448  ]
  [ 73.259155    31.259155    15.259155  ]
  [ 74.15234     28.152344    13.152344  ]
  ...
  [207.9176      74.9176       0.52770996]
  [209.43481     78.434814     0.        ]
  [211.35461     80.354614     2.3546143 ]]

 [[ 72.74341     30.743408    14.743408  ]
  [ 77.          31.          16.        ]
  [ 76.8136      30.813599    14.813599  ]
  ...
  [209.26172     75.26172      2.2617188 ]
  [206.45691     71.6405       0.        ]
  [209.41919     77.41919      2.4191895 ]]

 [[ 75.35901     30.331665    15.007446  ]
  [ 79.59375     32.59375     16.59375   ]
  [ 79.          32.          14.        ]
  ...
  [203.67578     73.67578      0.        ]
  [204.8125      72.8125       0.        ]
  [209.          72.           0.        ]]

 ...

 [[  4.           0.           0.        ]
  [  5.6757812    1.           0.        ]
  [  5.           1.           0.        ]
  ...
  [ 19.039062    14.6953125   32.765625  ]


In [64]:
def scale(image, label):
  return image/255, label

In [65]:
train_ds=train_ds.map(scale)
for img,label in train_ds.take(3):
  print("Image:", img)
  print("Label:",label)

Image: tf.Tensor(
[[[0.2796449  0.13454686 0.07180176]
  [0.2872908  0.12258492 0.05983983]
  [0.2907935  0.11040135 0.05157782]
  ...
  [0.81536317 0.2937945  0.00206945]
  [0.821313   0.3075875  0.        ]
  [0.8288416  0.31511614 0.00923378]]

 [[0.28526828 0.12056238 0.05781729]
  [0.3019608  0.12156863 0.0627451 ]
  [0.3012298  0.12083764 0.05809254]
  ...
  [0.8206342  0.295144   0.00886948]
  [0.8096349  0.28094316 0.        ]
  [0.82125175 0.30360466 0.00948702]]

 [[0.29552552 0.11894771 0.05885273]
  [0.31213236 0.12781863 0.06507353]
  [0.30980393 0.1254902  0.05490196]
  ...
  [0.7987285  0.28892463 0.        ]
  [0.8031863  0.2855392  0.        ]
  [0.81960785 0.28235295 0.        ]]

 ...

 [[0.01568628 0.         0.        ]
  [0.02225797 0.00392157 0.        ]
  [0.01960784 0.00392157 0.        ]
  ...
  [0.07466299 0.05762868 0.12849265]
  [0.12706323 0.1126484  0.24481751]
  [0.13655981 0.10508004 0.22034983]]

 [[0.10670429 0.01103946 0.00237439]
  [0.09420908 0.007